### ISSUE TITLE
Do first - print parameters and stats to same file

### ISSUE THREAD

**Issue by agladstein** [agladstein/SimPrily#1]
Do this first.

At the very end of simprily.py, we make the two output files with the functions`write_results_file` and `write_sim_file`, which are in the script main_tools/houskeeping.py.

The sim file is two lines, containing a header and the parameter values.
The results file is two lines, containing a header and the calculated statistics.

Instead of writing two files, only write one file. The new file should be the two old files combined. The first line should be the header and the second line should be the parameter values and calculated statistics. 

Make a new function in main_tools/write_files.py called `write_sim_results_file`. Call the new file 
```
param_stat_file = '{}/param_stat_{}.txt'.format(dir, job)
```
where `dir` needs to be defined in the function `create_sim_directories` in the script main_tools/write_files.py.
Define `dir` as 
```
results_dir = str(path_name)+'/results'
```

You can then test that your new combined file is the same as the two old files combined.
Try a `paste param_file stat_file` on the command line to combine the two old files correctly.

**Comment by raflopjr** [comment]
Done. 

0742d886c6cdd0386b685581baa3d3a4aba311dd
