### ISSUE TITLE
required command line arguments

### ISSUE THREAD

**Issue by agladstein** [agladstein/SimPrily#2]
Change it so the only input arguments are:
1. param_file.txt
2. model_file.csv
3. jobID
4. output_dir
Read all other arguments from input file.

See README for how script is currently run with arguments.
Take a look at the Manual and examples to see how the model_file needs to be constructed.

Currently, the arguments are read into a dictionary and referred to by their key throughout the code, to make referencing them easier. This is done in `main_tools/housekeeping.py` in the function `process_args`. You will need to change the function `process_args` so it only contains 
```
'command'
'param file'
'model file'
'job'
'path'
``` 

The model file is read in `processInput.py` in the function `readModelFile` and `processInputFiles`.  In the model_file.csv, each new "command" must be on a new line, and on each line it must be separated by commas (white space is okay because it is stripped).

In the model_file.csv you should use the following flags:
```
-macs or -macsswig or -macs_file
-array
-germline
-nonrandom_discovery
```
The model_file.csv must include one of 3 options, `-macs`, `-macsswig`, or `-macs_file`. If it is not included in the model_file.csv, the program should stop and give an error message saying one of them needs to be included. Those three options should then function the same as they did as when they came from the argument. You can see they are used in an if statement on line 88, 107, and 117  of `simprily.py`. Following the `-macs` and `-macs_file` flags there should be a path to either the executable or static file. For example:
```
-macs, ./bin/macs
```
or 
```
-macs_file, tests/test_data/sites1000000.txt
```

After `-array` there should be a path to the SNP file. e.g.
```
-array, array_template/ill_650_test.bed
``` 

The flag `-germline` is optional. If it is provided, that should be the same as `0`. You can see the if statement is on line 188 of `simprily.py`.

The flag `-nonrandom_discovery` is optional. If it is provided, that should be the same as the "False" argument[7]. If it is not provided, it should be the same as "True".

Make sure you edit all the places the arguments are referred to in all the code.

**Comment by agladstein** [comment]
This is important and should be done soon. Although some of the other issues may be faster to complete.

**Comment by raflopjr** [comment]
so you want the number of arguments of simprily.py to be decreased to 5?

1. param_file.txt
2. model_file.csv
3. jobID
4. output_dir
5. other_arg_inputfile

**Comment by agladstein** [comment]
No, the remaining arguments should go in model_file.csv.
I'm updating the Issue now...

**Comment by agladstein** [comment]
Example model file:

```
-macs,./bin/macs,
-length,1000000,
-t,2.5e-8,
-s,1231,
-r,1e-8,
-h,1e5,
-R,genetic_map_b37/genetic_map_GRCh37_chr1.txt.macshs,
-I,2,20,140,
-n,1,A,
-n,2,B,
-ej_1,AB_t,2,1,
-en,AN_t,1,AN
-discovery,1
-sample,2
-daf,daf
-array, array_template/ill_650_test.bed
```

Runs as 
```
python simprily.py examples/eg1/param_file_eg1.txt examples/eg1/model_file_eg1.csv 1 output_dir
```
works with no error.

**Comment by kgurrola** [comment]
Changed all model files to have:
```-macs, ./bin/macs,```
Ran it using: 
```pt simprily.py examples/eg1/param_file_eg1.txt examples/eg1/model_file_eg1.csv 1 output_dir```
Interchanging the example numbers for 1, 3, 4, 6, 7
All completed successfully

Changed all model files to have:
```-macsswig,./bin/macs,```
Ran it using:
```pt simprily.py examples/eg1/param_file_eg1.txt examples/eg1/model_file_eg1.csv 1 output_dir```
Interchanging the example numbers for 1, 3, 4, 6, 7
All completed successfully

Changed all model files to have:
```-macsswig,```
Ran it using:
```pt simprily.py examples/eg1/param_file_eg1.txt examples/eg1/model_file_eg1.csv 1 output_dir```
interchanging the example numbers for 1, 3, 4, 6, 7

Got this error for all files using -macsswig,:
```Traceback (most recent call last):
  File "simprily.py", line 227, in <module>
    main(argv)
  File "simprily.py", line 51, in main
    processedData =  processInputFiles(args['param file'], args['model file'])
  File "/home/agladstein/Rafaels/SimPrily/processInput.py", line 337, in processInputFiles
    processedData = processModelData(variables, modelData) # creates the input for macsSwig
  File "/home/agladstein/Rafaels/SimPrily/processInput.py", line 170, in processModelData
    macs_args = [flags['-macsswig'][0][0], flags['-length'][0][0], "-I", flags['-I'][0][0]]
IndexError: list index out of range```
