### ISSUE TITLE
print space in results file

### ISSUE THREAD

**Issue by agladstein** [agladstein/SimPrily#29]
results file is being written with the parameter section and statistics section squished together - it needs a space between them.

results file is written with the function `write_sim_results_file` in `main_tools/write_files.py`.
It should have the form
```
parameter_header stats_header
parameter_values stats_values
```
An example of how it is now:
```
A	daf	B	AB_t	AN	AN_tSegS_D1_CGI	Sing_D1_CGI	Dupl_D1_CGI	TajD_D1_CGI	SegS_D1_ASC	Sing_D1_ASC	Dupl_D1_ASC	Pi_D1_ASC	TajD_D1_ASC	SegS_S1_ASC	Sing_S1_ASC	Dupl_S1_ASC	Pi_S1_ASC	TajD_S1_ASC	FST_D1_S1_ASC
44499.7180488	0.0264139586625	40008.4616861	(1600:4100)	10000.0	2113.439056124372	1724	590	-0.408906346485	165	27	11	57.4052631579	0.970678370999	158	4	1	49.1563206578	2.31756616044	0.0379303444817
```

You can see that `AN_tSegS_D1_CGI` is smushed together. there should be a space.

**Comment by agladstein** [comment]
difficulty - easy

**Comment by dcolson4** [comment]
@agladstein I pushed and think its fixed now.
