### ISSUE TITLE
Add a :benchmarking tag to the dockerfile that allows benchmarking

### ISSUE THREAD

**Issue by bjoyce3** [agladstein/SimPrily#36]
Simprily has benchmarking checkpoints set into it. Those are hidden because they slow down the code. Expose those in a special dockerfile tag so that we can use that in various builds for SCIENCE!

Much appreciated.

**Comment by agladstein** [comment]
Included `--profile` flag option to print log with time and memory usage.

See https://github.com/agladstein/SimPrily#input

Commit https://github.com/agladstein/SimPrily/commit/0cf7dc3e920cc8c31eb0aea465c694fecee99a19

Built with same Docker version1 tag
