### ISSUE TITLE
option to print ped and map files

### ISSUE THREAD

**Issue by agladstein** [agladstein/SimPrily#4]
make option in input model files to choose whether or not to print ped and map files.
In simprily.py there is a conditional,
```
        if using_pseudo_array:
            make_ped_file(ped_file_name, sequences)
            make_map_file(map_file_name, pos_asc, chr_number, avail_sites)
```
Change that so it is also conditioned on an option `-pedmap` in the model file or the `-germline` option.

currently, this option should only be available if following options are also included in the model file,  
```
-discovery
-sample
-daf
-array
```
If `-germline` or `-pedmap` are included in model file and if `using_pseudo_array` is true, then the ped and map files should be made.

**Comment by agladstein** [comment]
This can be done immediately and should not interfere with other issues.
difficulty - easy

**Comment by agladstein** [comment]
Also, if ped and map files aren't created, the directory `sim_data` should not be created, and if germline isn't run, the directory `germline_out` should not be created.

**Comment by dcolson4** [comment]
@agladstein i think its fixed 
see commit https://github.com/dcolson4/SimPrily/commit/1da74f716ebb6a904f8a0c1cc97c8d47562def97
do a pull request
